### PR TITLE
User style configuration

### PR DESCRIPTION
**Pull request by Themitchell**
Add configuration so style can be installed as usercss without userstyles.org

### CODE REVIEW

**Comment by wltjr** [comment]
Hi @Themitchell, thank you for the contribution!

If I understand the changes correctly, these modifications make it such that someone can click directly on the link from the README and have the style installed in Stylish. That seems acceptable. The PR/patch/diff is a little odd as several lines seem to be removed and added with no change. I may clean that up some as part of merge.

**Comment by wltjr** [comment]
Ah, there were trailing spaces on those lines, likely left over from line wrapping in nano.

**Comment by Themitchell** [comment]
Hi, 

Yes the changes made are so that the user css can be installed directly and updated based on the github source avoiding the use of userstyles.org.

You are correct my editor must have added the whitespace changes. I can fix that locally and will edit the PR. 

The style is great so thanks for your work :)

**Comment by Themitchell** [comment]
Ok removed the whitespace changes to improve the diff. 👍

**Comment by wltjr** [comment]
Cool, thanks for the modifications. I will likely make the same to some other styles to make it easier for others. No worries on the white space. I will remove them with another commit, unless you want to. At first, i was viewing the PR via the github patch/diff feature, where you add that suffix onto the URL. That did not show the trailing white space, which confused me as to why the lines were being modified. When I viewed the PR via Github's website, I could see the trailing white space so it made more sense.

Definitely want to get rid of the white space. No need to revise your PR again. Plus, better off in a separate stand alone commit, as most prefer the small changes in their own commits, for one reason or another. Minor here, but a habit I like to adhere to.

I will merge this later today, time permitting. Thanks again for the contribution and glad you found the style beneficial!

**Comment by wltjr** [comment]
@Themitchell I merged the commit, but something is off in my work flow. The PR did not auto close as merged like PR #3. I will be revisiting this to correct that once I figure out what I did off this time... If you have to force pull or see other oddities that is why.

**Comment by Themitchell** [comment]
No worries, thanks for the update. And great style :)

**Pull request merged**
