### PR TITLE
travis ci dark: various fixes

### PR DESCRIPTION
**Pull request by the-j0k3r**
This includes fixes for Travis landing page and when logged into Travis.

This removes the purple color for now, in order to fix several issues I had to separate the group that had the purple color.

I tried fixing the loading issue mentioned in https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/issues/1#issuecomment-386163632 however I think this is not possible, but Im not some expert in css I will coninue to look for how to fix that.

Known issues: 
- [ ] The jobs-list hover effect is not working same as unstyled in fact the normal shown a big border which should only show when hover.
- [x] Broken hover on https://travis-ci.org/kvirc/KVIrc/requests
- [ ] The `job-env is-empty` is too dark in comparison with text around it, its also a little hard to read, no idea how to fix that atm.
- [x] The Tooltips text color for some reason does not obey the color: attribute, the only solution I found to make tooltips readable is to make the background darker.
- [ ] Some hover/non hover selectors are still mixed in same group, this causes some issues with fine tuning.
- [x] Notice banner is not styled accordingly
- [x] Broken `yml-messages` `messages` box and contents https://travis-ci.org/travis-ci/travis-build/builds/374363908?utm_source=github_status&utm_medium=notification
- [ ] Broken fade at `commit:description::after` commit hash see https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2#issuecomment-386282958 for possible solution. 
- [x] Broken white borders in https://travis-ci.org/travis-ci/travis-build/requests
- [x] Broken white borders in https://travis-ci.org/travis-ci/travis-build/builds
- [x] Broken fade issue at https://travis-ci.org/travis-ci/travis-build with `.commit-description::after`
- [ ] Secondary navigation should match the default, travis bug I bet but OK. 
- [x] @wltjr loading page white boarders issue

Todo: 
- [ ] Fix above
- [x] Add header to style with version etc.
- [ ] Add base color as purple and user selectable base color like github dark @wltjr  for that job as that requires access to stylish as well.
- [ ] Add a better README

I think the future would be better as a base color of your preference and a user selectable color at stylish at install time like GitHub Dark. That way you can still take theme to many machines, that said I will keep my own style for now without any special colors, thers much work to be done here before that can be done.

### CODE REVIEW

**Comment by wltjr** [comment]
Sweet thanks! I will see about merging tomorrow and tweaking. I may upload 2 versions, one without the purple and the purple one. That way I can keep my purple and you do not have to be subjected to that. Maybe can do a branch and rebase for any changes or something, since the only difference will be a color. Then again I can always make that change for my release of dark purple.

Thanks for taking a look at the issue I mentioned on the missing element. It is surely possible. Just have to find out what element it is, or the class or id of the element. It loads and goes away so fast I cannot inspect the page fast enough to see the element. I may have to try to disconnect internet and cause the page to hang on that. I tried hitting stop but it proceeds anyway. Its a pain...

I will see if I can address the other issues you mentioned. I was not aware of them, so since I know where to go look. I can see about adding styles for that stuff.

Thanks again, more to come tomorrow!

**Comment by the-j0k3r** [comment]
I pushed a few more fixes.

Im having trouble with fixing the top item on the known issues list, its a mess :/ trial and error, error wins so far Looking at the original travis.css helps none :-1: .

with latest fix this is how it looks at https://travis-ci.org/travis-ci/travis-build/builds/374363908?utm_source=github_status&utm_medium=notification 

capture

though I just noticed an issue at https://travis-ci.org/travis-ci/travis-build.

capture

sigh...

**Comment by the-j0k3r** [comment]
https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2/commits/5f7297f96a26efe343dc9daac8e9bdd589198853 fixes 

capture

**Comment by the-j0k3r** [comment]
Im now frustrated with trying to fix item 1 in known issues, Im leaving it for now as is.

**Comment by the-j0k3r** [comment]
Im able to half fix item 2 in known issues with

```css
  .request-item.approved.ember-view:hover {
	  border-left: solid 3px #39aa56 !important;
	  background-color: #164322 !important;
	  color: #c0c0c0 !important;
  }
```

Here is a preview of before and after

selectors

However there is that dark gradient on the right of every cell that I am out of ideas how to get rid of.

The rest looks as it should more or less.

**Comment by the-j0k3r** [comment]
Perhaps @mottie or @silverwind would be kind enough to share some tricks with these cluster-frock ;)

**Comment by wltjr** [comment]
@the-j0k3r that dark gradient comes from a hover. I had to fix/add it in some places. That or the background color is not set or missing on hover. I grabbed your PR modifications but haven't had a chance to check it out or see about anything not addressed. I will ASAP, just busy with some other things. Also seems your proceeding with somethings, so no problem with leaving it open for a bit for most stuff to be addressed. Though there can always be other PRs later.

Once again thank you for your time and contributions! Much appreciated!

**Comment by the-j0k3r** [comment]
> that dark gradient comes from a hover. I had to fix/add it in some places.

Ah, well Ive no idea because that makes it look weird, how to fix?

>I will ASAP, just busy with some other things. Also seems your proceeding with somethings, so no problem with leaving it open for a bit for most stuff to be addressed.

Well Im stuck in some areas like item 1 and that item 2 in  https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2#issuecomment-386341895 which could use some help in fixing without that black hover thing.

I just fixed item 9 in https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2/commits/90d33c1b6fec7653a462f2e68370b02ffcac146a

**Comment by wltjr** [comment]
Ok, I will look into the stuff your stuck on. I started with web development long ago, so pretty decent skills there. Just a time thing. Web development is a major time killer...

The gradient roll over your seeing I have fixed in other areas. Thus I have an idea what the cause is, and the fix is a matter of finding the right element, and at times nesting with other things like ```:hover``` etc. Some stuff has ```::before``` and ```::after```. Those are difficult because unlike most HTML elements. They will appear and disappear in the actual HTML. No one codes those its a browser thing I think. I do not recall typing in ```::after``` or ```::before``` into a HTML page, but I have used that in CSS styling. Though I could be off there. Those came about after I was doing less web dev and more actual coding.

I will for sure help out. Just have bugs in other stuff I am working on, just juggling the work load, packaging, fixing, coding, styling etc :)

**Comment by the-j0k3r** [comment]
I think I may have found a weird way to fix it... item 2 that is.

Just like the fix I havent pushed at https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2#issuecomment-386282958 it involves adding a `margin: 23px !important;` to https://github.com/the-j0k3r/Travis-CI-Dark-Purple/blob/e53c6c235fc394f584be190b9a642a52a6206bb0/travis-ci-dark-purple.css#L16-L39

Im not sure on that fix though, but I will push the changes with a warning.

**Comment by the-j0k3r** [comment]
OK, I found the problem with a little of looking with open eyes.

You actually added a dark fade which makes things look weird imo, so I went all transparent instead and fixed item 2 in https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2/commits/f3d1adc11ee6e47ab5435c9a41f3d0ffe3ee1fb0 you can see what I did I hope thats OK.

unstyled and styled gif
selectors

A similar fix for item 11 https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2/commits/23ec2331f28e4af586dc91970a38a4d5fdc2de87 again I went for transparent.

Im still stuck on item 1, for guidance so you know what Im working towards is like item 2 does only at this page https://travis-ci.org/travis-ci/travis-build

**Comment by Mottie** [comment]
In GitHub-Dark we use the following definition for brown. It looks halfway decent:

```css
.brown {
  background: rgba(51, 34, 17, .4) !important;
  border: 1px solid #542 !important;
  color: #ddd !important;
}
```

**Comment by wltjr** [comment]
I think that brown maybe another thing I changed in my GitHub Dark Purple. I do not see any browns that I can recall. Though it maybe there on some pages I do not visit.

The issue for Travis is that area has a very subtle background and border colors. It looks a bit odd to have that stand out, the contrast. You can barely tell there is a background or border. Very light yellow.
shot-2018-05-03_20-32-56

I guess brown makes sense for that. I just do not think it looks as clean as the version I had with no background or border. Thus I think a good medium would be like a gray or something that does not contrast as much against the black background. Like the light yellow before was barely noticeable from all the blinding white light :see_no_evil:

**Comment by the-j0k3r** [comment]
> I think that brown maybe another thing I changed in my GitHub Dark Purple. I do not see any browns that I can recall. Though it maybe there on some pages I do not visit.

The brown I added in https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2/commits/1619862990e7e3c2dd8ee7d46ca4a4e1513665d7 to more or less match GitHub-Dark
This looks OK as a notice, its yellow unstyled but GitHub-Dark does it decently, better than all dark all the time.

There is too much black and gray imo

> I think the fading is from this commit.

Im not sure what you referr to exactly, fading is what there was before and it breaks other elements.

**Comment by the-j0k3r** [comment]
OK, I found the problem with a little of looking with open eyes.

You actually added a dark fade which makes things look weird imo, so I went all transparent instead and fixed item 2 in https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2/commits/f3d1adc11ee6e47ab5435c9a41f3d0ffe3ee1fb0 you can see what I did I hope thats OK.

unstyled and styled gif
selectors

A similar fix for item 11 https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2/commits/23ec2331f28e4af586dc91970a38a4d5fdc2de87 again I went for transparent.

Im still stuck on item 1, for guidance so you know what Im working towards is like item 2 does only at this page https://travis-ci.org/travis-ci/travis-build




> In GitHub-Dark we use the following definition for brown. It looks halfway decent:

thanks Ill use those colors too here... :D that will make it match :D

**Comment by wltjr** [comment]
@Mottie finally seeing the brown on github dark, for pull request reviews. I had not seen that before. The same comments I made for Travis applies there. It is a subtle contrast normally on github, and the brown seems to make it stand out much more, bit to much contrast.
shot-2018-05-03_21-32-09

**Comment by wltjr** [comment]
@the-j0k3r your issue 1 is actually more complex. The entire row is supposed to change color, very light color green, red, yellow, or gray. That is lost in my theme, and also has a thicker golored border on roll over. The hover effects there and styling is quite tricky.

That is one of those places I was saying the css ```::before``` and ```::after``` is used, and those come and go. Its a difficult area to style.

**Comment by the-j0k3r** [comment]
> @the-j0k3r your issue 1 is actually more complex. The entire row is supposed to change color, very light color green, red, yellow, or gray. That is lost in my theme, and also has a thicker colored border on roll over. The hover effects there and styling is quite tricky.

Like I said in my other reply, your style doesnt follow the standard travis because as this issue proves, inverting things doesnt works as you would think here for whatever reason.

I think however judging by your comments that you are unhappy because a couple of areas broke which you had worked before and "fixed" and you feel that Im throwing your efforts away.

As is now, Im frustrated enough because Im trying to make the style work as if it were unstyled and that wont happen if it will be just invert and thats it as you say.

**Comment by the-j0k3r** [comment]
> In GitHub-Dark we use the following definition for brown. It looks halfway decent:
> 
> .brown {
>   background: rgba(51, 34, 17, .4) !important;
>   border: 1px solid #542 !important;
>   color: #ddd !important;
> }

its done in https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/pull/2/commits/ce934e7fbf606203edc8874596d5aa244e20c160

**Comment by wltjr** [comment]
Again the area your concerned with fixing I can address. I just do not have time for this right now. I can barely review. I am juggling lots of stuff, I mostly work with Java and C. CSS is pretty basic for me in that sense. Just spend time on bigger things. Like coding a display manager that supports X and Wayland, both running under either and launching sessions. Also discussing a new build system for Gentoo, etc.

I had not finished dialing in my style to address all the default elements of Travis that were lost like the row colors on hover. I had enough difficulties there styling other stuff and only have so much time for stuff that really is moot for my professional work. Why its been a while since I last touched it. Why I can barely comment on stuff vs participate in your efforts at the moment.

**Comment by the-j0k3r** [comment]
Im in no rush for my part, I have some time ATM so Im doing what I can.

**Comment by wltjr** [comment]
This was like a day or so at best, but ok no worries. I never said I was happy or complete. It was an initial work in progress I will further as time permits.

Not sure why your focused on skills, I was just saying things are possible you are struggling with. I had my own struggles. I very much dislike web dev for various reasons. It takes considerable time to do things that really should not take such time. When CSS carried over to Java via JavaFX for UIs i was not excited. There was just recent a raging debate on Netbeans development mailing list over such topics....

Sorry you felt like closing. Bit of patience there would have helped. But no worries, thanks again!

**Comment by the-j0k3r** [comment]
> Not sure why your focused on skills,

You have repeated several times in a few posts that you work with this lang and that lang and that css is more or less trivial and you are a web dev and this and that.

Im nothing of those things.

Im not taking credit for your work either as my work albeit amateurish is for personal use and if I ever publish you will get your credits, I dont feel we can collaborate however and thats is entirely on me, sorry.

**Comment by wltjr** [comment]
I just mentioned that because you were getting frustrated and felt somethings were not possible. I was simply saying they were. I am not a web dev, I am a programmer and systems administrator at times. For programmers web development and CSS is some what basic. Programming is more complex.

Sorry you feel as you do, but no worries. This is not really major stuff. I would not really feel one way or another over it. I did it on a whim one day. I still have other aspects of SonarCloud to do as well. But my time must go towards things that pay the bills.

**Comment by wltjr** [comment]
The dark hacks you refer to once again are just Travis features inverted. They fade from white to nothing. When you invert to black you fade from black to nothing. Anyway you are welcome to proceed with your own theme. I care less about credit on CSS stuff. I also told  you there was another theme as well. I was doing it for my needs. If others found it useful great.

But in your examples cut off text characters looks bad. Thus Travis had their design to fade characters rather than chop in half. You keep referring to that design as a hack... Anyway have fun with your Travis Dark.

**Comment by the-j0k3r** [comment]
I dont refer to those portions, in any case the point is the fade was preserved throughout, as I said it was a work in progress and the code you saw no longer exists.

I have based my style in the actual css from travis.web and not on your theme as I did originally, the style coverage in CI on my style is now 99% like for like with travis default, but dark and honoring GitHub-Dark design decisions in some notice banners etc.

There is still much refining to achieve that will come organically in time.

My goal is to have a smooth transition from GitHub-Dark -> Travis/AppVeyor/Other.

Ide like to apologise if I came across in the wrong way, frustration got the better of me.

Farewell.

**Pull request closed without merging**
