### PR TITLE
needed for travis-ci.com support

### PR DESCRIPTION
**Pull request by gpedro34**
travis-ci.org accounts are slowly being ported to travis-ci.com and ORG domain will eventually be dropped.

I just installed this stylish theme and as I really liked the theme and saw something to fix, jumped to it...

Hope you guys don't mind and that I followed the correct way of contributing to your repository...

EDIT: This is my first time doing a PR, so if I did something wrong please point that to me and if possible advise me on how I should do it instead. Thanks for understanding...

### CODE REVIEW

**Comment by wltjr** [comment]
Hi thanks! You did fine with the PR, good job. My only comments are 2 fold.
1. Try to follow commit message format for any project. Look at a few past commits and try to match that message format.
2. Only thing I had to correct/change, was the ordering of the class name you moved. It was minor, I just prefer it in alphabetical order.

They were pretty minor, mostly pet peeves of mine. The PR itself is fine. I am still somewhat new to working with PRs. I merged it already but not in a manner such that Gitub recognizes it and closes this PR and gives you credit on your profile stats. I will play with it a bit more, if you see some messages, or have to force pull, that is why. When I am done this should be closed as merged, you may want to wait till then to avoid any issues with me messing around.

Also thanks for the heads up on travis-ci.org -> travis-ci.com! I was not aware of such and likely need to update other repos, maybe my shield links.

**Comment by wltjr** [comment]
All done, though not in an ideal manner. I merged, pulled, modified the commit and force pushed, nastiness. I need to work on familiarizing myself with merging PRs on Github. Anyway thanks again!

**Comment by gpedro34** [comment]
Hi there... Hell yeah, my first ever PR and it gets merged!

I will remember about looking into other commits before doing mine next time. Commit comments is something I have been trying to change lately. Sometimes is hard to be concise and be able to clearly justify the changes at the same time...

Thanks for the feedback and I wouldn't consider it pet peeves, just good practice rules (everyone has theirs).

But to be completely honest I didn't even notice the classes were in alphabetic order before. Maybe add a CONTRIBUTING.md file in the repo with some of those rules would be a good idea.

Anyways glad you merged it and thank you for the plugin in the first place. It really feels good not having my eyes burning with all the clarity of Travis-CI... 😄

**Comment by wltjr** [comment]
I like to encourage others as much as possible, plus I need more experience in handling PRs, merging, etc.

The commit log format is just a personal pet peeve, some projects care, some do not. For a git commit, it is preferred to leave a short brief summary on the first line. Then, for additional information a more detailed description can follow the summary on additional lines, as many as needed, no length limitation, just within reason. Including any links or other information.

Your welcome for the feedback. It surely cannot hurt to have certain practices, like commit messages/log format. It really cannot hurt, and ideally should only help for projects that care about such things.

Thanks for the suggestion on a contributions file, I have added them in other repos. I think I will add them to the CSS ones as well. I would ideally like a screen shot of before and after, for visual justification of any changes. That way one does not have to "test out" or view the changes, they can see the problem and fix directly.

Thank you for the PR and fixes, even minor ones. Not sure when I would have noticed the travis-ci.com thing, and now that it is in place. I need to add more styles for travis-ci documentation. I am glad you found it beneficial. I think the world is slowly starting to realize for most things, white background is like a light in your face... Really noticeable at night if you flip between dark and light backgrounds.

**Pull request merged**
